version: 2.1
orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
    docker:
      - image: cypress/base:latest  # This image already has dependencies, but we'll ensure Xvfb is installed.
    environment:
      MONGODB_URI: "mongodb+srv://bertrandstanley:<BsMgdb@0225>@cluster0.awshp.mongodb.net/stanleyDB?retryWrites=true&w=majority&appName=Cluster0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Xvfb (for Cypress)
          command: sudo apt-get update && sudo apt-get install -y xvfb
      - run:
          name: Build the app
          command: npm run build

  run-tests:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Xvfb (for Cypress)
          command: sudo apt-get update && sudo apt-get install -y xvfb
      - run:
          name: Run Cypress tests
          command: npx cypress run --browser electron --headless

workflows:
  version: 2
  run-tests:
    jobs:
      - start-server
      - run-tests:
          requires:
            - start-server
