version: 2.1
# Make sure to add MONGODB_URI to ENVIRONMENT VARIABLES in CircleCI so that the tests can connect to the database
orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
    docker:
      - image: cypress/base:latest
    environment:
      MONGODB_URI: "mongodb+srv://bertrandstanley:<BsMgdb@0225>@cluster0.awshp.mongodb.net/stanleyDB?retryWrites=true&w=majority&appName=Cluster0" # This is just for demonstration; use CircleCI's environment variables instead for security!
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the app
          command: npm run build

  run-tests:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress tests
          command: npm run cypress:run

workflows:
  version: 2
  run-tests:
    jobs:
      - start-server
      - run-tests:
          requires:
            - start-server
